# Generated by Django 5.0.3 on 2024-04-17 12:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_system_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_name_list',
            name='jointime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_name_list',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users'),
        ),
    ]
