# Generated by Django 5.0.3 on 2024-04-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_name_list_jointime_alter_user_name_list_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_name_list',
            name='avatar',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
